version: '3.1'

networks:
  short-url-net:
    driver: bridge


# 如果你没有 MySQL 和 Redis 等依赖, 可以启动本 Docker Compose
services:
  mysql:
    image: mysql:8.0
    container_name: short-url-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: short-url
    ports:
      - "3306:3306"
#    volumes:
#      - ./deploy/data/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      # MySQL 就绪检测
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    privileged: true
    restart: always
    networks:
      - short-url-net
#
#  redis:
#    image: redis:6.2.5
#    container_name: interview-backend-redis
#    ports:
#      - "6379:6379"
#    environment:
#      TZ: Asia/Shanghai
#    volumes:
#      - ./deploy/data/redis/data:/data:rw
#    command: "redis-server"
#    privileged: true
#    restart: always
#    networks:
#      - interview-net
